model: 01-ai/Yi-34B-200K
replica_id: 0
replica_resource_mapping:
- !!python/tuple
  - node:192.168.0.44
  - 1
- !!python/tuple
  - node:192.168.0.44
  - 0
tokenizer: 01-ai/Yi-34B-200K
tokenizer_mode: auto
trust_remote_code: true
download_dir: null
load_format: dummy
dtype: float16
seed: 42
pipeline_parallel_size: 1
tensor_parallel_size: 2
block_size: 16
gpu_memory_utilization: 0.85
revision: null
scheduler_type: vllm
max_model_len: 1024
max_num_seqs: 8
max_num_batched_tokens: 1024
chunk_size: null
enable_dynamic_chunking_schedule: false
low_chunk_size: 128
high_chunk_size: 2048
chunk_schedule_max_tokens: 131072
chunk_schedule_stages: 16
write_metrics: true
output_dir: /home/sabiha/sarathi-serve/benchmark_output/figure-2//2026-02-10_23-46-05-196003/replica_0
wandb_project: llm-simulator
wandb_sweep_id: ''
wandb_run_id: ''
wandb_group: vllm_operation_time_split_experiment
wandb_run_name: Yi-34B-200K_tp_2_seq_len_1024_decode_batch_size_1_decode_split_f2142876
enable_op_level_metrics: false
enable_cpu_op_level_metrics: true
enable_chrome_trace: true
enable_request_outputs: false
keep_individual_batch_metrics: true
attention_backend: flash_attention
